spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vwcserverdb
    username: vwcuser
    password: vwcpassword
    platform: mysql
    initialization-mode: always
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  profiles: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
    