spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vwcserverdb?useUnicode=true&characterEncoding=utf8
    username: vwcuser
    password: vwcpassword
    platform: mysql
    initialization-mode: always
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?enabledTLSProtocols=TLSv1.2&useUnicode=true&characterEncoding=utf8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
 #   initialization-mode: always
    driverClassName: com.mysql.jdbc.Driver
  sql:
    init:
      enabled: true
  jpa:
    hibernate:
      ddlAuto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

---
spring:
  config:
    activate:
      on-profile: container
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?enabledTLSProtocols=TLSv1.2&useUnicode=true&characterEncoding=utf8
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: never
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddlAuto: none
      dialect: org.hibernate.dialect.MySQL5Dialect
 #   properties:
 #     hibernate:
 #       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
